In [1]:
import pandas as pd

In [2]:
!pwd

/Users/robertwittstock/Desktop/machine_learning/nasa


In [3]:
keppler_df = pd.read_csv('data/keppler_10_5_2025.csv',skiprows=53, on_bad_lines='skip')

In [4]:
keppler_df = keppler_df.drop(labels=['kepoi_name','kepler_name','koi_pdisposition','koi_score'],axis=1)

In [5]:
keppler_df

kepid koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0     10797460       CONFIRMED              0              0              0   
1     10797460       CONFIRMED              0              0              0   
2     10811496       CANDIDATE              0              0              0   
3     10848459  FALSE POSITIVE              0              1              0   
4     10854555       CONFIRMED              0              0              0   
...        ...             ...            ...            ...            ...   
9559  10090151  FALSE POSITIVE              0              1              1   
9560  10128825       CANDIDATE              0              0              0   
9561  10147276  FALSE POSITIVE              0              0              1   
9562  10155286       CANDIDATE              0              0              0   
9563  10156110  FALSE POSITIVE              0              0              1   

      koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  \
0                 0    9.488036     2.775000e-05    -2.775000e-05   
1                 0   54.418383     2.479000e-04    -2.479000e-04   
2                 0   19.899140     1.494000e-05    -1.494000e-05   
3                 0    1.736952     2.630000e-07    -2.630000e-07   
4                 0    2.525592     3.761000e-06    -3.761000e-06   
...             ...         ...              ...              ...   
9559              0    0.527699     1.160000e-07    -1.160000e-07   
9560              0    1.739849     1.780000e-05    -1.780000e-05   
9561              0    0.681402     2.434000e-06    -2.434000e-06   
9562              0  333.486169     4.235000e-03    -4.235000e-03   
9563              1    4.856035     6.356000e-05    -6.356000e-05   

      koi_time0bk  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0      170.538750  ...           -81.0      4.467           0.064   
1      162.513840  ...           -81.0      4.467           0.064   
2      175.850252  ...          -176.0      4.544           0.044   
3      170.307565  ...          -174.0      4.564           0.053   
4      171.595550  ...          -211.0      4.438           0.070   
...           ...  ...             ...        ...             ...   
9559   131.705093  ...          -166.0      4.529           0.035   
9560   133.001270  ...          -220.0      4.444           0.056   
9561   132.181750  ...          -236.0      4.447           0.056   
9562   153.615010  ...          -128.0      2.992           0.030   
9563   135.993300  ...          -225.0      4.385           0.054   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0             -0.096     0.927          0.105         -0.061  291.93423   
1             -0.096     0.927          0.105         -0.061  291.93423   
2             -0.176     0.868          0.233         -0.078  297.00482   
3             -0.168     0.791          0.201         -0.067  285.53461   
4             -0.210     1.046          0.334         -0.133  288.75488   
...              ...       ...            ...            ...        ...   
9559          -0.196     0.903          0.237         -0.079  297.18875   
9560          -0.224     1.031          0.341         -0.114  286.50937   
9561          -0.224     1.041          0.341         -0.114  294.16489   
9562          -0.027     7.824          0.223         -1.896  296.76288   
9563          -0.216     1.193          0.410         -0.137  297.00977   

            dec  koi_kepmag  
0     48.141651      15.347  
1     48.141651      15.347  
2     48.134129      15.436  
3     48.285210      15.597  
4     48.226200      15.509  
...         ...         ...  
9559  47.093819      14.082  
9560  47.163219      14.757  
9561  47.176281      15.385  
9562  47.145142      10.998  
9563  47.121021      14.826  

[9564 rows x 45 columns]

In [6]:
keppler_df['koi_disposition'].unique()

array(['CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE'], dtype=object)

In [7]:
tess_df = pd.read_csv('data/tess_10_5_2025.csv',skiprows=69,on_bad_lines='skip')

In [8]:
tess_df

toi        tid tfopwg_disp         rastr          ra         decstr  \
0     1000.01   50365310          FP  07h29m25.85s  112.357708  -12d41m45.46s   
1     1001.01   88863718          PC  08h10m19.31s  122.580465  -05d30m49.87s   
2     1002.01  124709665          FP  06h58m54.47s  104.726966  -10d34m49.64s   
3     1003.01  106997505          FP  07h22m14.39s  110.559945  -25d12m25.26s   
4     1004.01  238597883          FP  08h08m42.77s  122.178195  -48d48m10.12s   
...       ...        ...         ...           ...         ...            ...   
7698   995.01  317951248          FP  07h23m14.75s  110.811443  +05d33m46.26s   
7699   996.01  142918609          FP  07h57m23.99s  119.349948  -19d30m57.65s   
7700   997.01  341729521          FP  08h05m16.69s  121.319521  -59d34m47.27s   
7701   998.01   54390047          FP  07h53m16.69s  118.319555  -14d13m07.76s   
7702   999.01  341186896          FP  07h55m27.38s  118.864086  -58d13m19.42s   

            dec  st_pmra  st_pmraerr1  st_pmraerr2  ...  st_logg  st_loggerr1  \
0    -12.695960   -5.964        0.085       -0.085  ...     4.19         0.07   
1     -5.513852   -4.956        0.102       -0.102  ...     4.03         0.09   
2    -10.580455   -1.462        0.206       -0.206  ...      NaN          NaN   
3    -25.207017   -0.939        0.041       -0.041  ...     4.15         1.64   
4    -48.802811   -4.496        0.069       -0.069  ...     4.14         0.07   
...         ...      ...          ...          ...  ...      ...          ...   
7698   5.562850    2.061        0.405       -0.405  ...      NaN          NaN   
7699 -19.516015   -3.900        0.848       -0.848  ...      NaN          NaN   
7700 -59.579798  -44.770        0.044       -0.044  ...     4.52         0.08   
7701 -14.218823   -1.706        0.069       -0.069  ...     4.01         0.07   
7702 -58.222060  -17.190        0.042       -0.042  ...     4.35         0.09   

      st_loggerr2  st_logglim    st_rad  st_raderr1  st_raderr2  st_radlim  \
0           -0.07           0  2.169860    0.072573   -0.072573          0   
1           -0.09           0  2.010000    0.090000   -0.090000          0   
2             NaN           0  5.730000         NaN         NaN          0   
3           -1.64           0       NaN         NaN         NaN          0   
4           -0.07           0  2.150000    0.060000   -0.060000          0   
...           ...         ...       ...         ...         ...        ...   
7698          NaN           0       NaN         NaN         NaN          0   
7699          NaN           0  2.050000         NaN         NaN          0   
7700        -0.08           0  0.926261    0.045789   -0.045789          0   
7701        -0.07           0  2.349860    0.091578   -0.091578          0   
7702        -0.09           0  1.300000    0.050000   -0.050000          0   

              toi_created            rowupdate  
0     2019-07-24 15:58:33  2024-09-09 10:08:01  
1     2019-07-24 15:58:33  2023-04-03 14:31:04  
2     2019-07-24 15:58:33  2022-07-11 16:02:02  
3     2019-07-24 15:58:33  2022-02-23 10:10:02  
4     2019-07-24 15:58:33  2024-09-09 10:08:01  
...                   ...                  ...  
7698  2019-07-24 15:58:33  2021-10-29 12:59:15  
7699  2019-07-24 15:58:33  2021-10-29 12:59:15  
7700  2019-07-24 15:58:33  2024-09-09 10:08:01  
7701  2019-07-24 15:58:33  2024-09-09 10:08:01  
7702  2019-07-24 15:58:33  2024-09-09 10:08:01  

[7703 rows x 65 columns]

In [9]:
tess_df = tess_df.drop(labels=['toi','ra','rastr','dec','decstr','toi_created','rowupdate'],axis=1)

In [10]:
tess_df['tfopwg_disp'].unique()

array(['FP', 'PC', 'KP', 'APC', 'FA', 'CP'], dtype=object)

In [11]:
mapping = {
    'CP': 'CONFIRMED',
    'KP': 'CONFIRMED',
    'PC': 'CANDIDATE',
    'APC': 'CANDIDATE',
    'FP': 'FALSE POSITIVE',
    'FA': 'FALSE POSITIVE'
}

tess_df['disposition'] = tess_df['tfopwg_disp'].map(mapping)

In [12]:
tess_df

tid tfopwg_disp  st_pmra  st_pmraerr1  st_pmraerr2  st_pmralim  \
0      50365310          FP   -5.964        0.085       -0.085         0.0   
1      88863718          PC   -4.956        0.102       -0.102         0.0   
2     124709665          FP   -1.462        0.206       -0.206         0.0   
3     106997505          FP   -0.939        0.041       -0.041         0.0   
4     238597883          FP   -4.496        0.069       -0.069         0.0   
...         ...         ...      ...          ...          ...         ...   
7698  317951248          FP    2.061        0.405       -0.405         0.0   
7699  142918609          FP   -3.900        0.848       -0.848         0.0   
7700  341729521          FP  -44.770        0.044       -0.044         0.0   
7701   54390047          FP   -1.706        0.069       -0.069         0.0   
7702  341186896          FP  -17.190        0.042       -0.042         0.0   

      st_pmdec  st_pmdecerr1  st_pmdecerr2  st_pmdeclim  ...  st_tefflim  \
0       -0.076         0.072        -0.072          0.0  ...           0   
1      -15.555         0.072        -0.072          0.0  ...           0   
2       -2.249         0.206        -0.206          0.0  ...           0   
3        1.640         0.055        -0.055          0.0  ...           0   
4        9.347         0.062        -0.062          0.0  ...           0   
...        ...           ...           ...          ...  ...         ...   
7698    -7.082         0.336        -0.336          0.0  ...           0   
7699     3.866         1.158        -1.158          0.0  ...           0   
7700    -2.616         0.036        -0.036          0.0  ...           0   
7701    -1.714         0.061        -0.061          0.0  ...           0   
7702    12.272         0.039        -0.039          0.0  ...           0   

      st_logg  st_loggerr1  st_loggerr2  st_logglim    st_rad  st_raderr1  \
0        4.19         0.07        -0.07           0  2.169860    0.072573   
1        4.03         0.09        -0.09           0  2.010000    0.090000   
2         NaN          NaN          NaN           0  5.730000         NaN   
3        4.15         1.64        -1.64           0       NaN         NaN   
4        4.14         0.07        -0.07           0  2.150000    0.060000   
...       ...          ...          ...         ...       ...         ...   
7698      NaN          NaN          NaN           0       NaN         NaN   
7699      NaN          NaN          NaN           0  2.050000         NaN   
7700     4.52         0.08        -0.08           0  0.926261    0.045789   
7701     4.01         0.07        -0.07           0  2.349860    0.091578   
7702     4.35         0.09        -0.09           0  1.300000    0.050000   

      st_raderr2  st_radlim     disposition  
0      -0.072573          0  FALSE POSITIVE  
1      -0.090000          0       CANDIDATE  
2            NaN          0  FALSE POSITIVE  
3            NaN          0  FALSE POSITIVE  
4      -0.060000          0  FALSE POSITIVE  
...          ...        ...             ...  
7698         NaN          0  FALSE POSITIVE  
7699         NaN          0  FALSE POSITIVE  
7700   -0.045789          0  FALSE POSITIVE  
7701   -0.091578          0  FALSE POSITIVE  
7702   -0.050000          0  FALSE POSITIVE  

[7703 rows x 59 columns]

In [13]:
k2_df = pd.read_csv('data/k2_10_5_2025.csv',skiprows=98,on_bad_lines='skip')

In [14]:
k2_df

pl_name        hostname  default_flag disposition  \
0           BD+20 594 b       BD+20 594             0   CONFIRMED   
1           BD+20 594 b       BD+20 594             0   CONFIRMED   
2           BD+20 594 b       BD+20 594             1   CONFIRMED   
3     EPIC 201111557.01  EPIC 201111557             1   CANDIDATE   
4     EPIC 201111557.01  EPIC 201111557             0   CANDIDATE   
...                 ...             ...           ...         ...   
3999        WASP-85 A b       WASP-85 A             0   CONFIRMED   
4000         Wolf 503 b        Wolf 503             1   CONFIRMED   
4001         Wolf 503 b        Wolf 503             0   CONFIRMED   
4002         Wolf 503 b        Wolf 503             0   CONFIRMED   
4003         Wolf 503 b        Wolf 503             0   CONFIRMED   

                  disp_refname  sy_snum  sy_pnum discoverymethod  disc_year  \
0         Espinoza et al. 2016        1        1         Transit       2016   
1         Espinoza et al. 2016        1        1         Transit       2016   
2         Espinoza et al. 2016        1        1         Transit       2016   
3       Livingston et al. 2018        1        0         Transit       2018   
4       Livingston et al. 2018        1        0         Transit       2018   
...                        ...      ...      ...             ...        ...   
3999  Mo&#x10D;nik et al. 2016        2        1         Transit       2016   
4000      Peterson et al. 2018        1        1         Transit       2018   
4001      Peterson et al. 2018        1        1         Transit       2018   
4002      Peterson et al. 2018        1        1         Transit       2018   
4003      Peterson et al. 2018        1        1         Transit       2018   

     disc_facility  ... sy_vmagerr2  sy_kmag sy_kmagerr1  sy_kmagerr2  \
0               K2  ...      -0.012    9.368       0.018       -0.018   
1               K2  ...      -0.012    9.368       0.018       -0.018   
2               K2  ...      -0.012    9.368       0.018       -0.018   
3               K2  ...      -0.046    9.220       0.019       -0.019   
4               K2  ...      -0.046    9.220       0.019       -0.019   
...            ...  ...         ...      ...         ...          ...   
3999            K2  ...      -0.010    8.733       0.026       -0.026   
4000            K2  ...      -0.030    7.617       0.023       -0.023   
4001            K2  ...      -0.030    7.617       0.023       -0.023   
4002            K2  ...      -0.030    7.617       0.023       -0.023   
4003            K2  ...      -0.030    7.617       0.023       -0.023   

      sy_gaiamag  sy_gaiamagerr1  sy_gaiamagerr2   rowupdate  pl_pubdate  \
0       10.86440        0.000249       -0.000249  2018-04-25     2018-03   
1       10.86440        0.000249       -0.000249  2018-04-25     2016-10   
2       10.86440        0.000249       -0.000249  2018-04-25     2017-03   
3       11.39950        0.001307       -0.001307  2018-08-02     2018-08   
4       11.39950        0.001307       -0.001307  2018-02-15     2018-03   
...          ...             ...             ...         ...         ...   
3999    10.62410        0.000959       -0.000959  2019-09-05     2019-09   
4000     9.89816        0.000337       -0.000337  2022-05-23     2021-12   
4001     9.89816        0.000337       -0.000337  2018-09-04     2018-11   
4002     9.89816        0.000337       -0.000337  2023-04-17     2023-04   
4003     9.89816        0.000337       -0.000337  2025-09-17     2017-07   

      releasedate  
0      2018-02-15  
1      2016-07-28  
2      2018-04-26  
3      2018-08-02  
4      2018-02-15  
...           ...  
3999   2019-09-05  
4000   2022-05-23  
4001   2018-09-06  
4002   2023-04-17  
4003   2025-08-28  

[4004 rows x 94 columns]

In [15]:
k2_df = k2_df.drop(labels=['hostname', 'pl_refname', 'st_refname', 'sy_refname', 'rowupdate', 'pl_pubdate', 'releasedate', 'discoverymethod', 'disc_year', 'disc_facility', 'soltype', 'default_flag', 'disp_refname', 'pl_controv_flag', 'pl_bmassprov'],axis=1)

In [16]:
k2_df

pl_name disposition  sy_snum  sy_pnum  pl_orbper  \
0           BD+20 594 b   CONFIRMED        1        1  41.688644   
1           BD+20 594 b   CONFIRMED        1        1  41.685500   
2           BD+20 594 b   CONFIRMED        1        1  41.685500   
3     EPIC 201111557.01   CANDIDATE        1        0   2.301830   
4     EPIC 201111557.01   CANDIDATE        1        0   2.302368   
...                 ...         ...      ...      ...        ...   
3999        WASP-85 A b   CONFIRMED        2        1   2.655676   
4000         Wolf 503 b   CONFIRMED        1        1   6.001270   
4001         Wolf 503 b   CONFIRMED        1        1   6.001180   
4002         Wolf 503 b   CONFIRMED        1        1   6.001270   
4003         Wolf 503 b   CONFIRMED        1        1        NaN   

      pl_orbpererr1  pl_orbpererr2  pl_orbperlim  pl_orbsmax  pl_orbsmaxerr1  \
0          0.003353      -0.003419           0.0         NaN             NaN   
1          0.003000      -0.003100           0.0     0.24100         0.01900   
2          0.003000      -0.003000           0.0         NaN             NaN   
3          0.000280      -0.000300           0.0         NaN             NaN   
4          0.000105      -0.000103           0.0         NaN             NaN   
...             ...            ...           ...         ...             ...   
3999       0.000002      -0.000002           0.0         NaN             NaN   
4000       0.000021      -0.000021           0.0     0.05706         0.00055   
4001       0.000080      -0.000110           0.0     0.05710         0.00200   
4002       0.000021      -0.000021           0.0     0.05712         0.00063   
4003            NaN            NaN           NaN         NaN             NaN   

      ...  sy_disterr2  sy_vmag  sy_vmagerr1  sy_vmagerr2  sy_kmag  \
0     ...      -1.2400   10.849        0.012       -0.012    9.368   
1     ...      -1.2400   10.849        0.012       -0.012    9.368   
2     ...      -1.2400   10.849        0.012       -0.012    9.368   
3     ...      -0.4598   11.727        0.046       -0.046    9.220   
4     ...      -0.4598   11.727        0.046       -0.046    9.220   
...   ...          ...      ...          ...          ...      ...   
3999  ...      -1.2080   10.720        0.010       -0.010    8.733   
4000  ...      -0.0961   10.270        0.030       -0.030    7.617   
4001  ...      -0.0961   10.270        0.030       -0.030    7.617   
4002  ...      -0.0961   10.270        0.030       -0.030    7.617   
4003  ...      -0.0961   10.270        0.030       -0.030    7.617   

      sy_kmagerr1  sy_kmagerr2  sy_gaiamag  sy_gaiamagerr1  sy_gaiamagerr2  
0           0.018       -0.018    10.86440        0.000249       -0.000249  
1           0.018       -0.018    10.86440        0.000249       -0.000249  
2           0.018       -0.018    10.86440        0.000249       -0.000249  
3           0.019       -0.019    11.39950        0.001307       -0.001307  
4           0.019       -0.019    11.39950        0.001307       -0.001307  
...           ...          ...         ...             ...             ...  
3999        0.026       -0.026    10.62410        0.000959       -0.000959  
4000        0.023       -0.023     9.89816        0.000337       -0.000337  
4001        0.023       -0.023     9.89816        0.000337       -0.000337  
4002        0.023       -0.023     9.89816        0.000337       -0.000337  
4003        0.023       -0.023     9.89816        0.000337       -0.000337  

[4004 rows x 79 columns]

In [17]:
keppler_df['mission'] = 'Keppler'
k2_df['mission'] = 'K2'


In [18]:
tess_df['mission'] = 'Tess'

In [19]:
keppler_df['label_text'] = keppler_df['koi_disposition']
k2_df['label_text'] = k2_df['disposition']
tess_df['label_text'] = tess_df['disposition']

In [20]:
import numpy as np
from numpy import hypot

In [21]:
k2_u = pd.DataFrame({
    'period_days': k2_df['pl_orbper'],
    'duration_hr': np.nan,
    'depth_ppm':   np.nan,
    'impact':      np.nan,
    'snr_model':   np.nan,
    'planet_radius_re': k2_df['pl_rade'],
    'planet_mass_me':   k2_df['pl_bmasse'],
    'insol_eflux': k2_df['pl_insol'],
    'eqt_k':       k2_df['pl_eqt'],
    'eccentricity':k2_df['pl_orbeccen'],
    'star_teff_k': k2_df['st_teff'],
    'star_logg_cgs': k2_df['st_logg'],
    'star_radius_rsun': k2_df['st_rad'],
    'star_metallicity_dex': k2_df['st_met'],
    'mag_mission': k2_df['sy_gaiamag'].fillna(k2_df['sy_vmag']).fillna(k2_df['sy_kmag']),
    'distance_pc': k2_df['sy_dist'],
    'pm_tot_masyr': np.nan,
    'mission': k2_df['mission'],
    'label_text': k2_df['label_text'],
    'id': k2_df['pl_name']
})

In [22]:
keppler_u = pd.DataFrame({
    'period_days': keppler_df['koi_period'],
    'duration_hr': keppler_df['koi_duration'],
    'depth_ppm':   keppler_df['koi_depth'],
    'impact':      keppler_df['koi_impact'],
    'snr_model':   keppler_df['koi_model_snr'],
    'planet_radius_re': keppler_df['koi_prad'],
    'planet_mass_me':   np.nan,
    'insol_eflux': keppler_df['koi_insol'],
    'eqt_k':       keppler_df['koi_teq'],
    'eccentricity':np.nan,
    'star_teff_k': keppler_df['koi_steff'],
    'star_logg_cgs': keppler_df['koi_slogg'],
    'star_radius_rsun': keppler_df['koi_srad'],
    'star_metallicity_dex': np.nan,
    'mag_mission': keppler_df['koi_kepmag'],
    'distance_pc': np.nan,
    'pm_tot_masyr': np.nan,
    'mission': keppler_df['mission'],
    'label_text': keppler_df['label_text'],
    'id':keppler_df['kepid']
})

In [23]:

tess_u = pd.DataFrame({
    'period_days': tess_df['pl_orbper'],
    'duration_hr': tess_df['pl_trandurh'],
    'depth_ppm':   tess_df['pl_trandep'],
    'impact':      np.nan,
    'snr_model':   np.nan,
    'planet_radius_re': tess_df['pl_rade'],
    'planet_mass_me':   np.nan,
    'insol_eflux': tess_df['pl_insol'],
    'eqt_k':       tess_df['pl_eqt'],
    'eccentricity':np.nan,
    'star_teff_k': tess_df['st_teff'],
    'star_logg_cgs': tess_df['st_logg'],
    'star_radius_rsun': tess_df['st_rad'],
    'star_metallicity_dex': np.nan,
    'mag_mission': tess_df['st_tmag'],
    'distance_pc': tess_df['st_dist'],
    'pm_tot_masyr': hypot(tess_df['st_pmra'].fillna(0), tess_df['st_pmdec'].fillna(0)),
    'mission': tess_df['mission'],
    'label_text': tess_df['label_text'],
    'id': tess_df['tid']
})

In [24]:
df = pd.concat([k2_u, keppler_u, tess_u], ignore_index=True)

In [25]:
mapping = {
    'FALSE POSITIVE': 0,
    'CANDIDATE': 1,
    'CONFIRMED': 2,
    'REFUTED': 0
}
df['y'] = df['label_text'].map(mapping)

In [26]:
df['label_text'].unique()

array(['CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'REFUTED'],
      dtype=object)

In [27]:
# ---------- Engineer features ----------
def safe_div(a, b):
    a, b = np.asarray(a, dtype=float), np.asarray(b, dtype=float)
    out = np.divide(a, b, out=np.full_like(a, np.nan, dtype=float), where=(b!=0))
    return out

# duty cycle
df['duty_cycle'] = safe_div(df['duration_hr']/24.0, df['period_days'])

# radius ratio & predicted depth
rprs = safe_div(df['planet_radius_re']*0.0091577, df['star_radius_rsun'])
df['rprs'] = rprs
df['depth_pred_ppm'] = (rprs**2)*1e6
df['depth_resid_ppm'] = df['depth_ppm'] - df['depth_pred_ppm']

# density (Earth units)
df['rho_rel'] = safe_div(df['planet_mass_me'], df['planet_radius_re']**3)

# simple logs for skew
for c_old, c_new in [
    ('period_days','log_period'),
    ('depth_ppm','log_depth'),
    ('insol_eflux','log_insol'),
    ('distance_pc','log_dist'),
]:
    df[c_new] = np.log1p(df[c_old])

# Optional: missingness flags for key cols
for c in ['depth_ppm','duration_hr','planet_radius_re','star_radius_rsun','star_teff_k','mag_mission']:
    df[f'{c}_miss'] = df[c].isna().astype(int)

In [28]:
df.columns

Index(['period_days', 'duration_hr', 'depth_ppm', 'impact', 'snr_model',
       'planet_radius_re', 'planet_mass_me', 'insol_eflux', 'eqt_k',
       'eccentricity', 'star_teff_k', 'star_logg_cgs', 'star_radius_rsun',
       'star_metallicity_dex', 'mag_mission', 'distance_pc', 'pm_tot_masyr',
       'mission', 'label_text', 'id', 'y', 'duty_cycle', 'rprs',
       'depth_pred_ppm', 'depth_resid_ppm', 'rho_rel', 'log_period',
       'log_depth', 'log_insol', 'log_dist', 'depth_ppm_miss',
       'duration_hr_miss', 'planet_radius_re_miss', 'star_radius_rsun_miss',
       'star_teff_k_miss', 'mag_mission_miss'],
      dtype='object')

In [29]:
features = [
    'period_days','duration_hr','depth_ppm','impact','snr_model',
    'planet_radius_re','planet_mass_me','insol_eflux','eqt_k','eccentricity',
    'star_teff_k','star_logg_cgs','star_radius_rsun','star_metallicity_dex',
    'mag_mission','distance_pc','pm_tot_masyr',
    'duty_cycle','rprs','depth_pred_ppm','depth_resid_ppm','rho_rel',
    'log_period','log_depth','log_insol','log_dist',
    # simple missingness indicators
    'depth_ppm_miss','duration_hr_miss','planet_radius_re_miss',
    'star_radius_rsun_miss','star_teff_k_miss','mag_mission_miss',
    # (optional) mission one-hot if you plan to blend sources but keep domain cue:
    # add after get_dummies below
]

X = df[features]
y = df['y']

In [30]:
y.unique()

array([2, 1, 0])

# Baseline model

In [37]:
from sklearn.model_selection import StratifiedKFold, cross_val_predict, train_test_split, ParameterGrid
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.inspection import permutation_importance
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.base import clone

In [32]:
# Clean infs from engineered logs
X = X.replace([np.inf, -np.inf], np.nan)

# Preprocess: HGB can handle NaNs, but impute to keep pipeline model-agnostic
num_cols = X.columns.tolist()
preprocess = ColumnTransformer([
    ("num", Pipeline([
        ("impute", SimpleImputer(strategy="median")),
        ("scale", StandardScaler(with_mean=False))
    ]), num_cols)
], remainder="drop")

# Inverse-frequency sample weights for imbalance
class_counts = y.value_counts().to_dict()
weights = y.map({k: 1.0/v for k, v in class_counts.items()}).values

model = HistGradientBoostingClassifier(
    loss="log_loss",
    learning_rate=0.05,
    max_depth=6,
    max_iter=400,
    early_stopping=True,
    validation_fraction=0.1,
    random_state=42
)

pipe = Pipeline([
    ("prep", preprocess),
    ("clf", model)
])


skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

y_pred = np.empty(len(y), dtype=int)
# If you also want calibrated probabilities:
y_proba = np.zeros((len(y), len(np.unique(y))), dtype=float)

for fold, (tr, te) in enumerate(skf.split(X, y), 1):
    est = clone(pipe)  # pipe = Pipeline([("prep", preprocess), ("clf", model)])
    est.fit(X.iloc[tr], y.iloc[tr], clf__sample_weight=weights[tr])
    y_pred[te]  = est.predict(X.iloc[te])
    try:
        y_proba[te] = est.predict_proba(X.iloc[te])
    except AttributeError:
        pass  # some models may not have predict_proba

print(confusion_matrix(y, y_pred, labels=[0,1,2]))
print(classification_report(y, y_pred, target_names=["False Positive","Candidate","Confirmed"], digits=3))



[[4874 1173  402]
 [1202 6030 1262]
 [ 202  893 5233]]
                precision    recall  f1-score   support

False Positive      0.776     0.756     0.766      6449
     Candidate      0.745     0.710     0.727      8494
     Confirmed      0.759     0.827     0.791      6328

      accuracy                          0.759     21271
     macro avg      0.760     0.764     0.761     21271
  weighted avg      0.759     0.759     0.758     21271



In [33]:
# First: train (80%) + temp (20%)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Then: validation (10%) + test (10%)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

print(f"Train: {len(X_train)}, Validation: {len(X_val)}, Test: {len(X_test)}")

class_counts = y_train.value_counts().to_dict()
weights_train = y_train.map({k: 1.0/v for k, v in class_counts.items()}).values

pipe.fit(X_train, y_train, clf__sample_weight=weights_train)

# Validation
y_val_pred = pipe.predict(X_val)
print("VALIDATION SET")
print(confusion_matrix(y_val, y_val_pred, labels=[0,1,2]))
print(classification_report(
    y_val, y_val_pred,
    target_names=["False Positive","Candidate","Confirmed"],
    digits=3
))

# Test
y_test_pred = pipe.predict(X_test)
print("TEST SET")
print(confusion_matrix(y_test, y_test_pred, labels=[0,1,2]))
print(classification_report(
    y_test, y_test_pred,
    target_names=["False Positive","Candidate","Confirmed"],
    digits=3
))


Train: 17016, Validation: 2127, Test: 2128
VALIDATION SET
[[490 122  33]
 [110 612 127]
 [ 22  89 522]]
                precision    recall  f1-score   support

False Positive      0.788     0.760     0.773       645
     Candidate      0.744     0.721     0.732       849
     Confirmed      0.765     0.825     0.794       633

      accuracy                          0.764      2127
     macro avg      0.766     0.768     0.766      2127
  weighted avg      0.763     0.764     0.763      2127

TEST SET
[[494 114  37]
 [119 613 118]
 [ 19  93 521]]
                precision    recall  f1-score   support

False Positive      0.782     0.766     0.774       645
     Candidate      0.748     0.721     0.734       850
     Confirmed      0.771     0.823     0.796       633

      accuracy                          0.765      2128
     macro avg      0.767     0.770     0.768      2128
  weighted avg      0.765     0.765     0.765      2128



In [36]:
# First: train (80%) + temp (20%)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Then: validation (10%) + test (10%)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

print(f"Train: {len(X_train)}, Validation: {len(X_val)}, Test: {len(X_test)}")

class_counts = y_train.value_counts().to_dict()
weights_train = y_train.map({k: 1.0/v for k, v in class_counts.items()}).values

param_grid = {
    "clf__max_depth": [4, 6, 8],
    "clf__learning_rate": [0.03, 0.05, 0.08],
    "clf__l2_regularization": [0.0, 0.1, 0.5],
}

best_params, best_f1 = None, -np.inf
best_model = None

for params in ParameterGrid(param_grid):
    est = clone(pipe)
    # turn off internal early-stopping so it doesn't carve out its own val split
    est.set_params(**params, clf__early_stopping=False, clf__max_iter=400, clf__random_state=42)
    est.fit(X_train, y_train, clf__sample_weight=weights_train)
    y_val_pred = est.predict(X_val)
    f1 = f1_score(y_val, y_val_pred, average="macro")
    if f1 > best_f1:
        best_f1, best_params, best_model = f1, params, est

print("Best params (validation macro-F1 = {:.3f}):".format(best_f1), best_params)

# Detailed validation report for the best model
from sklearn.metrics import confusion_matrix
y_val_pred = best_model.predict(X_val)
print("VALIDATION (best model)")
print(confusion_matrix(y_val, y_val_pred, labels=[0,1,2]))
print(classification_report(y_val, y_val_pred,
      target_names=["False Positive","Candidate","Confirmed"], digits=3))

# ---- Refit on TRAIN+VAL with best params, then evaluate on TEST ----
X_trv = pd.concat([X_train, X_val], axis=0)
y_trv = pd.concat([y_train, y_val], axis=0)

class_counts_trv = y_trv.value_counts().to_dict()
weights_trv = y_trv.map({k: 1.0/v for k, v in class_counts_trv.items()}).values

final_pipe = clone(pipe)
final_pipe.set_params(**best_params, clf__early_stopping=False, clf__max_iter=400, clf__random_state=42)
final_pipe.fit(X_trv, y_trv, clf__sample_weight=weights_trv)

y_test_pred = final_pipe.predict(X_test)
print("TEST (refit on train+val)")
print(confusion_matrix(y_test, y_test_pred, labels=[0,1,2]))
print(classification_report(y_test, y_test_pred,
      target_names=["False Positive","Candidate","Confirmed"], digits=3))

Train: 17016, Validation: 2127, Test: 2128
Best params (validation macro-F1 = 0.769): {'clf__l2_regularization': 0.0, 'clf__learning_rate': 0.08, 'clf__max_depth': 8}
VALIDATION (best model)
[[484 131  30]
 [109 626 114]
 [ 20  95 518]]
                precision    recall  f1-score   support

False Positive      0.790     0.750     0.769       645
     Candidate      0.735     0.737     0.736       849
     Confirmed      0.782     0.818     0.800       633

      accuracy                          0.765      2127
     macro avg      0.769     0.769     0.769      2127
  weighted avg      0.766     0.765     0.765      2127

TEST (refit on train+val)
[[499 114  32]
 [114 640  96]
 [ 19  79 535]]
                precision    recall  f1-score   support

False Positive      0.790     0.774     0.782       645
     Candidate      0.768     0.753     0.761       850
     Confirmed      0.807     0.845     0.826       633

      accuracy                          0.787      2128
     macro avg

In [38]:
# final_train_export.py
import os, json, joblib, hashlib, sys
from datetime import datetime


# ======= Inputs you already have in memory / notebook =======
# df            : your unified dataframe
# features      : the exact list you trained with
# y (0/1/2)     : df['y']  where 0=FP, 1=CANDIDATE, 2=CONFIRMED
# best params   : {'clf__max_depth': 8, 'clf__learning_rate': 0.08, 'clf__l2_regularization': 0.0}
# ============================================================

LABEL_MAP = {0: "FALSE POSITIVE", 1: "CANDIDATE", 2: "CONFIRMED"}

# 1) Build X, y from full data (ALL rows)
X_full = df[features].copy().replace([np.inf, -np.inf], np.nan)
y_full = df['y'].astype(int).copy()

# 2) Preprocess (same as before)
num_cols = X_full.columns.tolist()
preprocess = ColumnTransformer([
    ("num", Pipeline([
        ("impute", SimpleImputer(strategy="median")),
        ("scale",  StandardScaler(with_mean=False)),
    ]), num_cols)
], remainder="drop")

# 3) Final model with tuned params + early stopping for generalization
clf = HistGradientBoostingClassifier(
    loss="log_loss",
    max_depth=8,
    learning_rate=0.08,
    l2_regularization=0.0,
    max_iter=1000,
    early_stopping=True,
    validation_fraction=0.1,
    n_iter_no_change=20,
    random_state=42
)

pipe = Pipeline([
    ("prep", preprocess),
    ("clf", clf)
])

# 4) Optional: inverse-frequency sample weights (computed on all data)
class_counts = y_full.value_counts().to_dict()
weights_full = y_full.map({k: 1.0/v for k, v in class_counts.items()}).values

# 5) Fit the final model
pipe.fit(X_full, y_full, clf__sample_weight=weights_full)

# 6) Package metadata
export_dir = "model_export"
os.makedirs(export_dir, exist_ok=True)

timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H%M%SZ")
model_path = os.path.join(export_dir, f"exoplanet_model_tuned_all_{timestamp}.pkl")
meta_path  = os.path.join(export_dir, f"exoplanet_model_tuned_all_{timestamp}.meta.json")

joblib.dump(pipe, model_path)

# Compute a hash for integrity/versioning
with open(model_path, "rb") as f:
    model_bytes = f.read()
model_sha256 = hashlib.sha256(model_bytes).hexdigest()

meta = {
    "created_utc": timestamp,
    "model_file": os.path.basename(model_path),
    "model_sha256": model_sha256,
    "library": "scikit-learn",
    "sklearn_model": "HistGradientBoostingClassifier",
    "params": {
        "max_depth": 8,
        "learning_rate": 0.08,
        "l2_regularization": 0.0,
        "max_iter": 1000,
        "early_stopping": True,
        "validation_fraction": 0.1,
        "n_iter_no_change": 20,
        "random_state": 42
    },
    "label_map": LABEL_MAP,
    "features": features,
    "training_rows": int(len(X_full)),
    "class_counts": {int(k): int(v) for k, v in class_counts.items()},
    # Keep your previously reported test metrics here for reference
    "benchmark_test": {
        "macro_f1": 0.789,
        "accuracy": 0.787,
        "notes": "From earlier held-out test before final all-data retrain."
    }
}

with open(meta_path, "w") as f:
    json.dump(meta, f, indent=2)

print("Exported:")
print("  Model ->", model_path)
print("  Meta  ->", meta_path)

Exported:
  Model -> model_export/exoplanet_model_tuned_all_2025-10-06T032756Z.pkl
  Meta  -> model_export/exoplanet_model_tuned_all_2025-10-06T032756Z.meta.json
